### ISSUE TITLE
Update AIND batch preprocessing function

### ISSUE THREAD

**Issue by rachelstephlee** [AllenNeuralDynamics/aind-fip-dff#1]
There are two identical functions `batch_processing_new` and `batch_processing`

This should be consolidated. Per @BrianNGitahi , they are waiting if Johannes will add to the batch_processing function, hence they created two versions.

**Comment by jeromelecoq** [comment]
Johannes will start adding his method: Double exponential.

**Comment by alexpiet** [comment]
Motion correction also needs to be implemented

**Comment by jeromelecoq** [comment]
@j-friedrich working on this.

**Comment by jeromelecoq** [comment]
Maybe consider adding a description of the Algo as a markdown file in the fiber document here : https://github.com/AllenNeuralDynamics/aind-physio-arch/tree/main/doc/teams/fiber

**Comment by j-friedrich** [comment]
- Added markdown file to https://github.com/AllenNeuralDynamics/aind-physio-arch/tree/main/doc/teams/fiber
-  Opened (PR)[https://github.com/AllenNeuralDynamics/aind-fip-dff/pull/7]

**Comment by jeromelecoq** [comment]
Moving to testing, separate ticket.
