### ISSUE TITLE
easy way to differentiate between behavior and fiber data

### ISSUE THREAD

**Issue by rachelstephlee** [AllenNeuralDynamics/aind-fip-dff#13]
It's difficult to find assets that have fiber photometry data and only have behavior. They should be tagged correctly when created as an asset.

**Comment by alexpiet** [comment]
Is this redundant with https://github.com/AllenNeuralDynamics/aind-physio-arch/issues/71 ?

**Comment by rachelstephlee** [comment]
we can fold it in, good point !
