### ISSUE TITLE
Patch for Iso channel column number error

### ISSUE THREAD

**Issue by hagikent** [AllenNeuralDynamics/aind-fip-dff#21]
The issue is described here.
https://github.com/AllenNeuralDynamics/aind-behavior-blog/issues/735

Briefly, large fraction of Iso channel data.csv files have 9 columns instead of 6 (timestamp, ROI0, 1, 2, 3, Blank). Practically, this is not an issue as what happens is having three additional columns with all 0. As real data should be with values >255, the erroneous columns are easy to be eliminated.
![Screenshot 2024-11-22 at 3 35 14](https://github.com/user-attachments/assets/e4bef6de-543c-404e-8148-7ac679c78cbe)

This issue has been caused by an bug in the following Bonsai code (will fix this shortly). The node should be `Activity.val0` instead of `Activity`.
![Screenshot 2024-11-22 at 2 56 56](https://github.com/user-attachments/assets/ba63ead4-05e7-4970-8c47-dcc77fc5907c)

As this is confusing (why 9 columns? why different from other two channels?), we should take care of this before nwb packaging.
Also, some pilot data acquired in 2023Late have only 4columns—Timestamp, ROI0, ROI1, Blank. This should be handled by a patch too.

**Comment by jeromelecoq** [comment]
Plan to fix early January.

**Comment by rachelstephlee** [comment]
This is fixed on the experimenter rig. 

When we will be processing older data, we will fix the pipeline side as well. 
- Will need to eliminate some 0-filled data.
