### ISSUE TITLE
ValueError: all the input array dimensions except for the concatenation axis must match exactly,

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/aind-fip-dff#24]
Sessions are crashing: https://codeocean.allenneuraldynamics.org/data-assets/b059b50d-0a77-43ce-bc74-1534d3bf875d/behavior_757209_2024-12-02_15-22-46_processed_2024-12-03_06-59-19/output?fullScreen=true&hideDetails=true

**Comment by j-friedrich** [comment]
This has been fixed with above PR [#59](https://github.com/AllenNeuralDynamics/aind-fip-nwb-base-capsule/pull/59) and the pipeline capsules have been synced as well. Yay!
