### ISSUE TITLE
statsmodels.tools.sm_exceptions.MissingDataError: exog contains inf or nans

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/aind-fip-dff#25]
NaNs in the processing: https://codeocean.allenneuraldynamics.org/data-assets/b58012b3-d877-4252-864d-46d2641ec08d/behavior_757212_2024-12-03_16-14-06_processed_2024-12-04_05-22-32/output?fullScreen=true&hideDetails=true

**Comment by j-friedrich** [comment]
Fixed with commit [3399918](https://github.com/AllenNeuralDynamics/aind-fip-dff/commit/33999182efe9dfd4e342534fa82bb54135e480a0)
