### ISSUE TITLE
  ValueError: NaN, inf or invalid value detected in weights, estimation infeasible.

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/aind-fip-dff#27]

**Comment by j-friedrich** [comment]
Fixed with commits 77b81d80b5a4a6ddfce95792dc15a3cdaf6d5b67 and 77b81d80b5a4a6ddfce95792dc15a3cdaf6d5b67.
@Ahad-Allen still needs to sync the capsule with Github

**Comment by j-friedrich** [comment]
My commits are synced by now and used in the pipeleine
