### ISSUE TITLE
FIP timeseries is incorrectly aligned

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/aind-fip-dff#5]
Looking at the NWB files generated from the pipeline there are two issues with time alignment
- The R channel timestamps start ~30s after the G channel. They should be synchronized

![Image](https://github.com/user-attachments/assets/275c7198-0cf7-4dcb-8ca2-8b7f2398bd04)

- The G,R,Iso timestamps are not synchronized (likely a result of the first issue)

![Image](https://github.com/user-attachments/assets/240b46bd-8b4c-4913-9770-7d4ce0f2e7a7)

-

**Comment by hagikent** [comment]
this might be related to the handling of the "10 fist blank frames" that we used to have in the past

**Comment by alexpiet** [comment]
Note that debugging this code is very annoying because of this issues outlined here: https://github.com/AllenNeuralDynamics/aind-physio-arch/issues/45#issuecomment-2276796729

**Comment by rachelstephlee** [comment]
Todo for rachel: 

Write a testing function that will eventually be integrated into the QC code.

**Comment by alexpiet** [comment]
@srecanatesi gives this fix, editing line 460 of "aligned_fiber_to_nwb.py" which reads:
```
        timestamps[channel] = df_fip_sel[df_fip_sel['channel'] == channel]['time_fip'].values
```
to 
```
        timestamps_channel = df_fip_sel[df_fip_sel['channel'] == channel]['time_fip'].values
        conversion_factor = np.round(statistics.mode(np.round(np.diff(timestamps_channel),2))/0.05)
        power = 10**round(np.log10(abs(conversion_factor)))
        timestamps[channel] = timestamps_channel / power

```

This appears to resolve the issue. Remaining tasks:
- [ ] add this line to the pipeline
- [ ] Add a QC check to look for this issue in the future
- [ ] Test on more sessions

**Comment by alexpiet** [comment]
- PR to update the pipeline. https://github.com/AllenNeuralDynamics/NWB-Packaging-FiberPhotometry-Base-Capsule/pull/14
- I'm struggling to test it on CO, because I'm not familiar with CO tools.

**Comment by alexpiet** [comment]
![Image](https://github.com/user-attachments/assets/cb5d3983-ee48-4fe7-a0b3-c3c21ea5601b)

**Comment by hagikent** [comment]
If easily debugable, I wouldn't discourage to do so. However, practically, we can completely drop the "falling" from nwb or dataframe. 

Rationale:
-rising is corresponding to the starting time of Green channel camera frame exposure
-falling is corresponding to the ending time of Green channel camera frame exposure
-Green channel one data point has only one (Bonsai-software) timestamp and thus only one HARP-aligned timestamp.
-thus, the only one additional info we have by keeping falling is the exposure time (diff between rising and falling)

**Comment by alexpiet** [comment]
Making a list of sessions where the alignment is to ISO, and not G1

BAD:
behavior_717531_2024-08-07_09-01-02_processed_2024-08-08_13-34-22 (but still has 30 second offset issue)

GOOD:
behavior_711042_2024-08-23_13-27-08_processed_2024-08-24_07-39-12
behavior_717531_2024-08-23_08-58-49_processed_2024-08-24_10-37-56
behavior_732163_2024-08-23_13-36-21_processed_2024-08-24_06-57-41
