### ISSUE TITLE
Refactor Pipeline code

### ISSUE THREAD

**Issue by rachelstephlee** [AllenNeuralDynamics/aind-fip-dff#8]
See [#45](https://github.com/AllenNeuralDynamics/aind-physio-arch/issues/45) for more information. 

Generally, the issue is that there are a lot of functions that are duplicated across. We need to refactor to clean up the code. 

Copying Alex's description here: 

In this capsule: https://codeocean.allenneuraldynamics.org/capsule/9216710/tree (NWB-Packaging-FiberPhotometry-Base-Capsule)
- The functions in `util` should live in a library that can be imported, otherwise its very difficult to run these functions outside of code ocean, and if we want to re-use those functions in another capsule we have to copy the code manually. 
   - In fact, code is already being manually copied into https://github.com/AllenNeuralDynamics/aind-fip-dff ! We should absolutely not have the exact same functions in two capsules in the same pipeline. 
- The code in `util.aligned_fiber_to_nwb.py` has lots of commented out blocks of code, and needs a general cleaning/linting

In this repo https://github.com/AllenNeuralDynamics/aind-fip-dff, there are a lot of mentions of "old" and "new" processing methods. These should be replaced with descriptive versions of how the code works. No one will remember in a year what old and new mean.

**Comment by alexpiet** [comment]
Util functions should be moved to this repo: https://github.com/AllenNeuralDynamics/aind-fib-utils

**Comment by Ahad-Allen** [comment]
I've moved NWB util functions to the util repo, I am not sure if preprocessing functions should exist here or stay within the dff capsule, however. Should be easy to move them in either case.

**Comment by Ahad-Allen** [comment]
I recall @rachelstephlee did some work on the utils after my PR was merged, is my help still needed on this?

**Comment by rachelstephlee** [comment]
I didn't touch this, so if you think all the refactoring is completed, we can close this.
